# Generated by Django 4.2.9 on 2024-01-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adsb_hex', models.CharField(max_length=16)),
                ('altitude', models.IntegerField()),
                ('bearing', models.FloatField()),
                ('flight', models.CharField(max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('obs_time', models.DateTimeField(auto_now_add=True)),
                ('range', models.FloatField()),
                ('speed', models.IntegerField()),
                ('track', models.IntegerField()),
            ],
        ),
    ]
