# Generated by Django 4.2.9 on 2024-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0002_adsbexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=48, unique=True)),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('obs_time', models.DateTimeField(auto_now_add=True)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
