# Generated by Django 4.2.9 on 2024-03-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsbExchange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adsb_hex', models.CharField(max_length=16)),
                ('category', models.CharField(max_length=8)),
                ('emergency', models.CharField(max_length=8)),
                ('flight', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=24)),
                ('registration', models.CharField(max_length=12)),
                ('ladd_flag', models.BooleanField()),
                ('military_flag', models.BooleanField()),
                ('pia_flag', models.BooleanField()),
                ('wierdo_flag', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=48, unique=True)),
                ('load_time', models.DateTimeField(auto_now_add=True)),
                ('obs_time', models.DateTimeField(auto_now_add=True)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adsb_hex', models.CharField(max_length=16)),
                ('altitude', models.IntegerField()),
                ('bearing', models.FloatField()),
                ('flight', models.CharField(max_length=16)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('obs_time', models.DateTimeField(auto_now_add=True)),
                ('range', models.FloatField()),
                ('speed', models.IntegerField()),
                ('track', models.IntegerField()),
            ],
        ),
    ]
