# Generated by Django 4.2.9 on 2024-03-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyena', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsbRanking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adsb_hex', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=24)),
                ('population', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('registration', models.CharField(max_length=12)),
                ('score_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BoxScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adsb_hex_total', models.IntegerField()),
                ('adsb_hex_new', models.IntegerField()),
                ('device', models.CharField(max_length=32)),
                ('file_population', models.IntegerField()),
                ('refresh_flag', models.BooleanField()),
                ('score_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Cooked',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('adsb_hex', models.CharField(max_length=16)),
                ('observed_counter', models.IntegerField()),
                ('observed_first', models.DateTimeField(auto_now_add=True)),
                ('observed_last', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=132)),
            ],
        ),
    ]
