#!/bin/sh -e

case "$1" in
    configure)
        echo "xxx xxx configure xxx xxx"

        chown wombat:crontab wombat

        chown wombat:wombat /home/wombat/.bash_aliases
        chown -R wombat:wombat /home/wombat/Documents

        chown -R wombat:wombat /var/wombat

        ;;

    abort-install|abort-upgrade|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
