# Generated by Django 4.2.9 on 2024-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('crate_id', models.IntegerField()),
                ('crate_location', models.CharField(max_length=32)),
                ('crate_name', models.CharField(max_length=32)),
            ],
        ),
    ]
