# Generated by Django 4.2.9 on 2025-03-01 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wombat', '0002_heeler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heeler',
            name='frequency_mhz',
            field=models.IntegerField(),
        ),
    ]
