---
- name: pull-dump1090
  become: true
  hosts: "{{ target_hosts }}"
  tasks:
    - name: ensure github directory exists
      ansible.builtin.file:
        path: "/home/wombat/github"
        state: directory
        owner: wombat
        group: wombat
        mode: "0755"

    - name: clone or pull dump1090
      become: false
      ansible.builtin.git:
        repo: https://github.com/flightaware/dump1090.git
        dest: "/home/wombat/github/dump1090"
        update: yes
