---
- name: pull-rtlsdr
  become: true
  hosts: "{{ target_hosts }}"
  tasks:
    - name: ensure github directory exists
      ansible.builtin.file:
        path: "/home/wombat/github"
        state: directory
        owner: wombat
        group: wombat
        mode: "0755"

    - name: clone or pull rtl-sdr
      become: false
      ansible.builtin.git:
        repo: https://github.com/osmocom/rtl-sdr.git
        dest: "/home/wombat/github/rtl-sdr"
        update: yes
