---
- name: reboot
  hosts: "{{ target_hosts }}"
  become: true
  become_user: root
  tasks:
   - name: reboot
     ansible.builtin.reboot:

   - name: print message
     ansible.builtin.debug:
       msg: reboot
